name: Update Portfolio

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run DevFolio
        run: chmod +x devfolio.sh && ./devfolio.sh --username ${{ secrets.USERNAME }} --theme dark
      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Update portfolio" || exit 0
          git push